<a href="https://colab.research.google.com/github/Fawzy-AI-Explorer/-Gold-Price-Prediction./blob/main/labs_week1_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# lab1

In [116]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [117]:
X_train = np.array([[ 1 , 2 , 3 ],
                    [ 2 , 1 , 3 ]]
                   , dtype=np.float32)


Y_train = np.array([[300.0],
                    [500.0]],
                    dtype=np.float32)


In [118]:
x_train = X_train[0].reshape(-1,1)
x_train  #3*1

array([[1.],
       [2.],
       [3.]], dtype=float32)

In [119]:
linear_layer = tf.keras.layers.Dense(units=1, activation = 'linear', )
linear_layer(x_train)
linear_layer.get_weights() #1*1 ,b= 1*1

[array([[-1.1355891]], dtype=float32), array([0.], dtype=float32)]

In [120]:
linear_layer = tf.keras.layers.Dense(units=1, activation = 'linear', )
linear_layer(X_train)
linear_layer.get_weights()  #3*1, b=1*1

[array([[-1.1083611 ],
        [-0.13257182],
        [ 0.8758961 ]], dtype=float32),
 array([0.], dtype=float32)]

In [121]:
#each training example in a row
'''
[1]
[3]
[4]
3 tr ex. 1 feat

[1,2]
[3,7]
[4,9]
3 tr ex. 2 feat
'''

'\n[1]\n[3]\n[4]\n3 tr ex. 1 feat\n\n[1,2]\n[3,7]\n[4,9]\n3 tr ex. 2 feat\n'

In [122]:
sw = np.array([ [4],
                [5],
                [1] ])
sb =np.array( [0] )
linear_layer.set_weights([sw,sb])
linear_layer(X_train)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[17.],
       [16.]], dtype=float32)>

In [123]:
alin = np.dot ( X_train , sw ) + sb
             # 2*3    3*1     1*1
             #    2*1
alin


array([[17.],
       [16.]])

In [125]:
model = Sequential(
    [
        tf.keras.layers.Dense(1,  input_dim=3 , activation = 'sigmoid', name='L1')
    ]
)

model(X_train)  # 2*3
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 4         
                                                                 
Total params: 4 (16.00 Byte)
Trainable params: 4 (16.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [126]:
np.dot (X_train , sw) +sb

array([[17.],
       [16.]])

In [127]:
model(X_train)


<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.98572963],
       [0.9882335 ]], dtype=float32)>

# lab2


In [ ]:
# print(f"Temperature Max, Min pre normalization: {np.max(X[:,0]):0.2f}, {np.min(X[:,0]):0.2f}")
# print(f"Duration    Max, Min pre normalization: {np.max(X[:,1]):0.2f}, {np.min(X[:,1]):0.2f}")


# norm_l = tf.keras.layers.Normalization(axis=-1) #**************************************************************************************
# norm_l.adapt(X)  # learns mean, variance
# Xn = norm_l(X)




# print(f"Temperature Max, Min post normalization: {np.max(Xn[:,0]):0.2f}, {np.min(Xn[:,0]):0.2f}")
# print(f"Duration    Max, Min post normalization: {np.max(Xn[:,1]):0.2f}, {np.min(Xn[:,1]):0.2f}")

In [128]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [
        tf.keras.Input(shape=(2,)), #specifies the expected shape of the input This allows Tensorflow to size the weights and bias parameters at this point.
        Dense(3, activation='sigmoid', name = 'layer1'),
        Dense(1, activation='sigmoid', name = 'layer2')
     ]
)

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13 (52.00 Byte)
Trainable params: 13 (52.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [129]:
L1_num_params = 2 * 3 + 3   # W1 parameters  + b1 parameters
L2_num_params = 3 * 1 + 1   # W2 parameters  + b2 parameters
print("L1 params = ", L1_num_params, ", L2 params = ", L2_num_params  )

L1 params =  9 , L2 params =  4


In [130]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[ 0.6562191   0.9882722  -0.38974804]
 [-0.32380646  0.09636497 -0.5891686 ]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-1.049754 ]
 [-1.0710602]
 [-1.0590913]] 
b2(1,): [0.]


In [ ]:
# model.compile(                    #statement defines a loss function and specifies a compile optimization.
#     loss = tf.keras.losses.BinaryCrossentropy(),
#     optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
# )

# model.fit(                   #statement runs gradient descent and fits the weights to the data
#     Xt,Yt,
#     epochs=10,
# )


#### Epochs and batches
In the `fit` statement above, the number of `epochs` was set to 10. This specifies that the entire data set should be applied during training 10 times.  During training, you see output describing the progress of training that looks like this:
```
Epoch 1/10
6250/6250 [==============================] - 6s 910us/step - loss: 0.1782
```
The first line, `Epoch 1/10`, describes which epoch the model is currently running. For efficiency, the training data set is broken into 'batches'. The default size of a batch in Tensorflow is 32. There are 200000 examples in our expanded data set or 6250 batches ( 200000 / 32 = 6250). The notation on the 2nd line `6250/6250 [====` is describing which batch has been executed.

In [ ]:
200000 / 32

6250.0

Once you have a trained model, you can then use it to make predictions. Recall that the output of our model is a probability. In this case, the probability of a good roast. To make a decision, one must apply the probability to a threshold. In this case, we will use 0.5

In [131]:
X_test = np.array([
    [200,13.9],  # positive example
    [200,17]])   # negative example
# X_testn = norm_l(X_test)          #normalization
# predictions = model.predict(X_testn)
predictions = np.array([[9.89e-01] ,[4.94e-08]])
print("predictions = \n", predictions) #probability

predictions = 
 [[9.89e-01]
 [4.94e-08]]


predictions =
 [[9.89e-01]
 [4.94e-08]]

In [132]:
# To convert the probabilities to a decision, we apply a threshold:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[1.]
 [0.]]


In [133]:
#the same
yhat = (predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[1]
 [0]]


# lab3

In [134]:
np.zeros(3)

array([0., 0., 0.])

In [178]:
def g(z):
    return 1 / (1 + np.exp(-z))
#*****************************************
#*****************************************
#*****************************************
def my_dense(a_in, W, b):
    """
    Computes dense layer
    Args:
      a_in (ndarray (n, )) : Data, 1 example
      W    (ndarray (n,j)) : Weight matrix, n features per unit, j units
      b    (ndarray (j, )) : bias vector, j units
    Returns
      a_out (ndarray (j,))  : j units|
    """
    units = W.shape[1]          # num nodes in the next layer
    a_out = np.zeros(units)     # num nodes in the next layer
    for j in range(units):
        w = W[:,j]
        z = np.dot(w, a_in) + b[j]
        a_out[j] = g(z)
    return(a_out)
#*****************************************
#*****************************************
#*****************************************
def my_sequential(x, W1, b1, W2, b2):
    a1 = my_dense(x,  W1, b1)
    a2 = my_dense(a1, W2, b2)
    return(a2)
#*****************************************
#*****************************************
#*****************************************
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ],
                    [-0.1,  -7.32, 10.81]] )

b1_tmp = np.array( [-9.82, -9.28,  0.96] )

W2_tmp = np.array( [[-31.18],
                    [-27.59],
                    [-32.56]] )

b2_tmp = np.array( [15.41] )

#*****************************************
#*****************************************
#*****************************************

def my_predict(X, W1, b1, W2, b2):
    m = X.shape[0]              #num of training examoles
    p = np.zeros((m,1))
    for i in range(m):
        p[i,0] = my_sequential(X[i], W1, b1, W2, b2)
    return(p)
#*****************************************
#*****************************************
#*****************************************
X_tst = np.array([
    [200,13.9],  # postive example
    [200,17]])   # negative example


norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(X_tst)  # learns mean, variance
X_tst = norm_l(X_tst)


predictions = my_predict(X_tst, W1_tmp, b1_tmp, W2_tmp, b2_tmp)
predictions #probabilites


#*****************************************
#*****************************************
#*****************************************

# yhat = np.zeros_like(predictions)
# for i in range(len(predictions)):
#     if predictions[i] >= 0.5:
#         yhat[i] = 1
#     else:
#         yhat[i] = 0
# print(f"decisions = \n{yhat}")

# the same
yhat = (predictions >= 0.5).astype(int)
yhat

<ipython-input-178-47946687cf74>:52: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  p[i,0] = my_sequential(X[i], W1, b1, W2, b2)


array([[1],
       [0]])

array([[1],
       [0]])

# end week1

The data set contains 1000 training examples of handwritten digits  1
 , here limited to zero and one. <br>

Each training example is a 20-pixel x 20-pixel grayscale image of the digit.
Each pixel is represented by a floating-point number indicating the grayscale intensity at that location.<br>
The 20 by 20 grid of pixels is “unrolled” into a 400-dimensional vector.<br>
Each training example becomes a single row in our data matrix X.<br>
This gives us a 1000 x 400 matrix X where every row is a training example of a handwritten digit image.<br>


The second part of the training set is a 1000 x 1 dimensional vector y that contains labels for the training set<br>
y = 0 if the image is of the digit 0, y = 1 if the image is of the digit 1.<br>

The parameters have dimensions that are sized for a neural network with  25
  units in layer 1,  15 <br>
  units in layer 2 and  1 <br>
  output unit in layer 3. <br>

Recall that the dimensions of these parameters are determined as follows: <br>

If network has  𝑠𝑖𝑛
  units in a layer and  𝑠𝑜𝑢𝑡
  units in the next layer, then
𝑊
  will be of dimension  𝑠𝑖𝑛×𝑠𝑜𝑢𝑡
 .
𝑏
  will a vector with  𝑠𝑜𝑢𝑡
  elements
Therefore, the shapes of W, and b, are <br>

layer1: The shape of W1 is (400, 25) and the shape of b1 is (25,) <br>
layer2: The shape of W2 is (25, 15) and the shape of b2 is: (15,) <br>
layer3: The shape of W3 is (15, 1) and the shape of b3 is: (1,) <br>


In [147]:
'''
X, y = load_data()

model = Sequential(
    [
        tf.keras.Input(shape=(400,)),    #specify input size
        Dense(25 , activation = "sigmoid" , name = "l1"),
        Dense(15 , activation = "sigmoid" , name = "l2"),
        Dense(1  , activation = "sigmoid" , name = "l3")
      ], name = "my_model"
)
#1000 * 400 , w = [400 * 25] , b=[25] --> op = 1000 * 25
# 1000*25   , w = [25* 15] , b=[15]  ---> op = 1000 * 15
#1000 * 15  , w = [15 * 1] b=[1] ---->op = 1000 * 1

L1_num_params = 400 * 25 + 25  # W1 parameters  + b1 parameters
L2_num_params = 25 * 15 + 15   # W2 parameters  + b2 parameters
L3_num_params = 15 * 1 + 1     # W3 parameters  + b3 parameters




[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()


print(model.layers[2].weights) #layer 3

#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
# will define a loss function and run gradient descent to fit the weights of the model to the training data.
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X,y,
    epochs=20
)
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#******************************************************************************************************
#each example in a row (1*400) 400feature , 1 example
prediction = model.predict(X[0].reshape(1,400))  # a zero
print(f" predicting a zero: {prediction}")
prediction = model.predict(X[500].reshape(1,400))  # a one
print(f" predicting a one:  {prediction}")
if prediction >= 0.5:
    yhat = 1
else:
    yhat = 0
print(f"prediction after threshold: {yhat}")
'''

'\nX, y = load_data()\n\nmodel = Sequential(\n    [               \n        tf.keras.Input(shape=(400,)),    #specify input size\n        Dense(25 , activation = "sigmoid" , name = "l1"),\n        Dense(15 , activation = "sigmoid" , name = "l2"),\n        Dense(1  , activation = "sigmoid" , name = "l3")\n      ], name = "my_model" \n)                            \n#1000 * 400 , w = [400 * 25] , b=[25] --> op = 1000 * 25\n# 1000*25   , w = [25* 15] , b=[15]  ---> op = 1000 * 15\n#1000 * 15  , w = [15 * 1] b=[1] ---->op = 1000 * 1\n\nL1_num_params = 400 * 25 + 25  # W1 parameters  + b1 parameters\nL2_num_params = 25 * 15 + 15   # W2 parameters  + b2 parameters\nL3_num_params = 15 * 1 + 1     # W3 parameters  + b3 parameters\n\n\n\n\n[layer1, layer2, layer3] = model.layers\nW1,b1 = layer1.get_weights()\nW2,b2 = layer2.get_weights()\nW3,b3 = layer3.get_weights()\n\n\nprint(model.layers[2].weights) #layer 3 \n\n#********************************************************************************

In [176]:
a_in = np.array([ [1,2,3] ])

# W = [1,2,4]
W = np.array([ [1,2,3],
               [2,4,3],
               [7,2,3]])
# np.dot(a,w)



units = W.shape[1]

a_out = np.zeros(units)
# print(a_out[0])


# a_out[0] = [1]




# print(units , a_out)
for i in range (units):
    w = W[:,i]
    # print(w)
    z = np.dot(a_in,w) +1
    print(z)
    a_out[i] =  z



a_out

[27]
[17]
[19]


<ipython-input-176-0727f15cfd4a>:28: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a_out[i] =  z


array([27., 17., 19.])

In [ ]:
def my_dense_v(A_in, W, b, g):
    """
    Computes dense layer
    Args:
      A_in (ndarray (m,n)) : Data, m examples, n features each
      W    (ndarray (n,j)) : Weight matrix, n features per unit, j units
      b    (ndarray (1,j)) : bias vector, j units
      g    activation function (e.g. sigmoid, relu..)
    Returns
      A_out (tf.Tensor or ndarray (m,j)) : m examples, j units
    """
    z= np.dot(A_in , W) + b
    A_out = g(z)
    return(A_out)



def my_sequential_v(X, W1, b1, W2, b2, W3, b3):
    A1 = my_dense_v(X,  W1, b1, sigmoid)
    A2 = my_dense_v(A1, W2, b2, sigmoid)
    A3 = my_dense_v(A2, W3, b3, sigmoid)
    return(A3)

Prediction = my_sequential_v(X, W1_tmp, b1_tmp, W2_tmp, b2_tmp, W3_tmp, b3_tmp )
Prediction.shape

Yhat = (Prediction >= 0.5).astype(int)
print("predict a zero: ",Yhat[0], "predict a one: ", Yhat[500])

In [190]:
a = np.array([1,2,3]).reshape(-1,1)  #(3,1)
b = 5
c = a + b
# print(f"(a + b).shape: {(a + b).shape}, \na + b = \n{a + b}")
print(f"a:\n{a} \nb:\n {b}\nc:\n{c}")

print("*******************************")

w = a*b
print(f"a:\n{a} \nb:\n {b}\nw:\n{w}")


a:
[[1]
 [2]
 [3]] 
b:
 5
c:
[[6]
 [7]
 [8]]
*******************************
a:
[[1]
 [2]
 [3]] 
b:
 5
w:
[[ 5]
 [10]
 [15]]


In [191]:
a = np.array([1,2,3,4]).reshape(-1,1)
b = np.array([1,2,3]).reshape(1,-1)
print(a)
print(b)
print(f"(a + b).shape: {(a + b).shape}, \na + b = \n{a + b}")

[[1]
 [2]
 [3]
 [4]]
[[1 2 3]]
(a + b).shape: (4, 3), 
a + b = 
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
